# Generated by Django 4.2.5 on 2023-11-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_creacion', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=250)),
                ('documento', models.CharField(max_length=20)),
                ('documento_emision', models.CharField(choices=[('be', 'BE'), ('ch', 'CH'), ('co', 'CO'), ('lp', 'LP'), ('or', 'OR'), ('pa', 'PA'), ('po', 'PO'), ('sc', 'SC'), ('ta', 'TA'), ('na', 'Otro')], default='sc', max_length=2)),
                ('nacimiento_lugar', models.CharField(max_length=150)),
                ('nacimiento_fecha', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=250)),
                ('ocupacion', models.CharField(max_length=250)),
                ('notificaciones', models.BooleanField(default=True)),
            ],
        ),
    ]
