# Generated by Django 4.2.5 on 2023-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosasociado',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
